### ISSUE TITLE
Node panicked

### ISSUE THREAD

**Issue by darkfriend77** [ajuna-network/Ajuna#176]
**Description**

Setting up a archive node, panicked Version: 0.1.7-28d91f0318f 

```
0: sp_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/70b3681bf621bc0de91ffab711b2350068b4c466/library/std/src/[panicking.rs:702](http://panicking.rs:702/):17
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/70b3681bf621bc0de91ffab711b2350068b4c466/library/std/src/[panicking.rs:588](http://panicking.rs:588/):13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/70b3681bf621bc0de91ffab711b2350068b4c466/library/std/src/sys_common/[backtrace.rs:138](http://backtrace.rs:138/):18
   4: rust_begin_unwind
             at /rustc/70b3681bf621bc0de91ffab711b2350068b4c466/library/std/src/[panicking.rs:584](http://panicking.rs:584/):5
   5: core::panicking::panic_fmt
             at /rustc/70b3681bf621bc0de91ffab711b2350068b4c466/library/core/src/[panicking.rs:142](http://panicking.rs:142/):14
   6: core::result::unwrap_failed
             at /rustc/70b3681bf621bc0de91ffab711b2350068b4c466/library/core/src/[result.rs:1785](http://result.rs:1785/):5
   7: <sp_state_machine::ext::Ext<H,B> as sp_externalities::Externalities>::storage
   8: <&mut dyn sp_externalities::Externalities as sp_io::storage::Storage>::get_version_1
   9: std::thread::local::LocalKey<T>::with
  10: tracing::span::Span::in_scope
  11: sp_io::storage::get_version_1
  12: sp_io::storage::ExtStorageGetVersion1::call
  13: <sc_executor_wasmtime::imports::Registry as sp_wasm_interface::HostFunctionRegistry>::with_function_context
  14: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  15: <F as wasmtime::func::IntoFunc<T,(wasmtime::func::Caller<T>,A1),R>>::into_func::wasm_to_host_shim
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: wasmtime_runtime::traphandlers::catch_traps::call_closure
  20: wasmtime_setjmp
  21: wasmtime_runtime::traphandlers::<impl wasmtime_runtime::traphandlers::call_thread_state::CallThreadState>::with
  22: wasmtime_runtime::traphandlers::catch_traps
  23: wasmtime::func::invoke_wasm_and_catch_traps
  24: wasmtime::func::typed::TypedFunc<Params,Results>::call
  25: sc_executor_wasmtime::instance_wrapper::EntryPoint::call
  26: sc_executor_wasmtime::runtime::perform_call
  27: <sc_executor_wasmtime::runtime::WasmtimeInstance as sc_executor_common::wasm_runtime::WasmInstance>::call_with_allocation_stats
  28: sc_executor_common::wasm_runtime::WasmInstance::call_export
  29: std::panicking::try
  30: std::thread::local::LocalKey<T>::with
  31: sc_executor::native_executor::WasmExecutor<H>::with_instance::{{closure}}
  32: sc_executor::wasm_runtime::RuntimeCache::with_instance
  33: <sc_executor::native_executor::NativeElseWasmExecutor<D> as sp_core::traits::CodeExecutor>::call
  34: sp_state_machine::execution::StateMachine<B,H,Exec>::execute_aux
  35: sp_state_machine::execution::StateMachine<B,H,Exec>::execute_using_consensus_failure_handler
  36: <sc_service::client::call_executor::LocalCallExecutor<Block,B,E> as sc_client_api::call_executor::CallExecutor<Block>>::contextual_call
  37: <sc_service::client::client::Client<B,E,Block,RA> as sp_api::CallApiAt<Block>>::call_api_at
  38: sp_authority_discovery::AuthorityDiscoveryApi::authorities
  39: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  40: sc_authority_discovery::worker::Worker<Client,Network,Block,DhtEventStream>::run::{{closure}}
  41: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::poll
  42: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
  43: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  44: tokio::runtime::task::core::CoreStage<T>::poll
  45: tokio::runtime::task::harness::Harness<T,S>::poll
  46: std::thread::local::LocalKey<T>::with
  47: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  48: tokio::runtime::scheduler::multi_thread::worker::Context::run
  49: tokio::macros::scoped_tls::ScopedKey<T>::set
  50: tokio::runtime::scheduler::multi_thread::worker::run
  51: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
52: tokio::runtime::task::harness::Harness<T,S>::poll
  53: tokio::runtime::blocking::pool::Inner::run
  54: std::sys_common::backtrace::__rust_begin_short_backtrace
  55: core::ops::function::FnOnce::call_once{{vtable.shim}}
  56: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/70b3681bf621bc0de91ffab711b2350068b4c466/library/alloc/src/[boxed.rs:1872](http://boxed.rs:1872/):9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/70b3681bf621bc0de91ffab711b2350068b4c466/library/alloc/src/[boxed.rs:1872](http://boxed.rs:1872/):9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/70b3681bf621bc0de91ffab711b2350068b4c466/library/std/src/sys/unix/[thread.rs:108](http://thread.rs:108/):17
  57: start_thread
  58: clone

Thread 'tokio-runtime-worker' panicked at 'Externalities not allowed to fail within runtime: "Trie lookup error: Database missing expected key: 0xafd4e766a354dfeab9602d06e100e918d440dea2cefc85555ad6589747c0ded2"', /root/.cargo/git/checkouts/substrate-7e08433d4c370a21/2dff067/primitives/state-machine/src/[ext.rs:189](http://ext.rs:189/)

```
**Steps to Reproduce**

```
git clone https://github.com/ajuna-network/Ajuna.git
cd Ajuna
git checkout v0.1.7
cargo build-bajun-kusama
cp target/release/bajun-para /usr/bin/

nohup /usr/bin/bajun-para --chain=/root/data/Ajuna/resources/bajun/bajun-raw.json -d=/root/data/ --state-pruning=archive --rpc-external --rpc-port=$rpc_port --ws-external --ws-port=$ws_port --rpc-cors="*" --bootnodes=/ip4/[167.172.165.19/tcp/30333/ws/p2p/12D3KooWGtPZMr2Kvbt8b9qujuRRDsqrsA9855GsDDHWpnjzd7wF](http://167.172.165.19/tcp/30333/ws/p2p/12D3KooWGtPZMr2Kvbt8b9qujuRRDsqrsA9855GsDDHWpnjzd7wF) -- --chain=/root/data/Ajuna/resources/bajun/kusama.json  --rpc-external --rpc-port=9934 --ws-external --ws-port=9945 --no-telemetry --rpc-cors="*" >> ~/data/bajun-para.log 2>&1 &
```

**Expected vs. Actual Behavior**

_What did you expect to happen after you followed the steps you described in the last section? What
actually happened?_

**Environment**

```
rustup show
Default host: x86_64-unknown-linux-gnu
rustup home:  /root/.rustup

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu (default)
nightly-2022-05-15-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu

active toolchain
----------------

stable-x86_64-unknown-linux-gnu (default)
rustc 1.66.0 (69f9c33d7 2022-12-12)
```

**Logs, Errors or Screenshots**

_Please provide the text of any logs or errors that you experienced; if
applicable, provide screenshots to help illustrate the problem._

**Additional Information**

_Please add any other details that you think may help us solve your problem._

**Comment by cowboy-bebug** [comment]
It's working on my machine (commenting out ports):
```
./target/release/bajun-para --chain=resources/bajun/bajun-raw.json \
  -d=/tmp/bajun/ \
  --state-pruning=archive \
  --rpc-external \
  # --rpc-port=$rpc_port \
  --ws-external \
  # --ws-port=$ws_port \
  --rpc-cors="*" \
  --bootnodes=/ip4/167.172.165.19/tcp/30333/ws/p2p/12D3KooWGtPZMr2Kvbt8b9qujuRRDsqrsA9855GsDDHWpnjzd7wF \
  -- \
  --chain=/root/data/Ajuna/resources/bajun/kusama.json \
  --rpc-external \
  --rpc-port=9934 \
  --ws-external \
  --ws-port=9945 \
  --no-telemetry \
  --rpc-cors="*"
```

**Comment by cowboy-bebug** [comment]
@darkfriend77 - the bootnode flag seems to be incorrect. Could you specify the correct address?
```
--bootnodes=/ip4/167.172.165.19/tcp/30333/ws/p2p/12D3KooWGtPZMr2Kvbt8b9qujuRRDsqrsA9855GsDDHWpnjzd7wF
```

**Comment by darkfriend77** [comment]
closing this issue,

**_Trie lookup error: Database missing expected key: 0x..._**

seems to be linked to 

- https://github.com/paritytech/substrate/issues/3648
- https://github.com/paritytech/substrate/issues/1733

and didn't happened anymore.
