### ISSUE TITLE
Rococo Failure: Async Backing failing after settting to 6 sec into a panick.

### ISSUE THREAD

**Issue by darkfriend77** [ajuna-network/Ajuna#368]
**Description**

We updated to async backing and to the polkadot SDK v1.1.0 repo.

Which worked fine and produced block with the v0.1.24 

Changes for Async Backing
- https://github.com/ajuna-network/Ajuna/tree/v0.1.24 Worked

And then we add the changes to go for 6sec blocks and that started to panick, with v0.1.25
 - https://github.com/ajuna-network/Ajuna/tree/v0.1.25 Failed

**Expected vs. Actual Behavior**

Should not panicked.

**Logs, Errors or Screenshots**

```
2023-11-06 10:38:30 [Relaychain] :sparkles: Imported #7801225 (0x83d9…1f03)
2023-11-06 10:38:30 [Parachain] :raised_hands: Starting consensus session on top of parent 0x380479f1aa5aa1d55cb5366bd40afc213d8a94e58543ed140eff4816d33ce424
2023-11-06 10:38:30 [Parachain] Migration did not execute. This probably should be removed
2023-11-06 10:38:30 [Parachain] panicked at 'attempt to divide by zero', /home/builder/cargo/git/checkouts/polkadot-sdk-cff69157b985ed76/f60318f/substrate/primitives/consensus/slots/src/lib.rs:70:14
2023-11-06 10:38:30 [Parachain] 1 storage transactions are left open by the runtime. Those will be rolled back.
2023-11-06 10:38:30 [Parachain] 1 storage transactions are left open by the runtime. Those will be rolled back.
2023-11-06 10:38:30 [Parachain] :exclamation:️ Inherent extrinsic returned unexpected error: Error at calling runtime api: Execution failed: Execution aborted due to trap: wasm trap: wasm `unreachable` instruction executed
WASM backtrace:
error while executing at wasm backtrace:
    0: 0x372f84 - <unknown>!rust_begin_unwind
    1: 0x3228d2 - <unknown>!core::panicking::panic_fmt::hf5c4cd929d4aaa9e
    2: 0x322b33 - <unknown>!core::panicking::panic::h2f041bf6aa990dfd
    3: 0x29b307 - <unknown>!<cumulus_pallet_aura_ext::consensus_hook::FixedVelocityConsensusHook<T,_,_,_> as cumulus_pallet_parachain_system::consensus_hook::ConsensusHook>::on_state_proof::hb41607f68205e002
    4: 0x601ff - <unknown>!frame_support::storage::transactional::with_storage_layer::hb8293059a00b312d
    5: 0x2cbff2 - <unknown>!<cumulus_pallet_parachain_system::pallet::Call<T> as frame_support::traits::dispatch::UnfilteredDispatchable>::dispatch_bypass_filter::{{closure}}::h847eeed1c6663413
    6: 0x2d1fc9 - <unknown>!environmental::using_once::h842ff517359bc5c6
    7: 0x1b6597 - <unknown>!<bajun_runtime::RuntimeCall as frame_support::traits::dispatch::UnfilteredDispatchable>::dispatch_bypass_filter::h921d73cf99248ad3
    8: 0x1b90c6 - <unknown>!<bajun_runtime::RuntimeCall as sp_runtime::traits::Dispatchable>::dispatch::h1e953c0ad270c4d2
    9: 0x14ed8d - <unknown>!<sp_runtime::generic::checked_extrinsic::CheckedExtrinsic<AccountId,Call,Extra> as sp_runtime::traits::Applyable>::apply::h63066e3dd511455b
   10: 0x27d0f5 - <unknown>!frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPalletsWithSystem,COnRuntimeUpgrade>::apply_extrinsic::hb105ce907a92d0f9
   11: 0x2a7896 - <unknown>!BlockBuilder_apply_extrinsic. Dropping.
2023-11-06 10:38:30 [Parachain] panicked at 'Aura slot duration cannot be zero.', /home/builder/cargo/git/checkouts/polkadot-sdk-cff69157b985ed76/f60318f/substrate/frame/aura/src/lib.rs:406:9
2023-11-06 10:38:30 [Parachain] 1 storage transactions are left open by the runtime. Those will be rolled back.
2023-11-06 10:38:30 [Parachain] 1 storage transactions are left open by the runtime. Those will be rolled back.
2023-11-06 10:38:30 [Parachain] :exclamation:️ Inherent extrinsic returned unexpected error: Error at calling runtime api: Execution failed: Execution aborted due to trap: wasm trap: wasm `unreachable` instruction executed
WASM backtrace:
error while executing at wasm backtrace:
    0: 0x372f84 - <unknown>!rust_begin_unwind
    1: 0x3228d2 - <unknown>!core::panicking::panic_fmt::hf5c4cd929d4aaa9e
    2: 0x41a29 - <unknown>!frame_support::storage::transactional::with_storage_layer::h3afb82a03700ac1e
    3: 0x2cf4c9 - <unknown>!environmental::using_once::h0bf9be8bd6bc1041
    4: 0x1b65e5 - <unknown>!<bajun_runtime::RuntimeCall as frame_support::traits::dispatch::UnfilteredDispatchable>::dispatch_bypass_filter::h921d73cf99248ad3
    5: 0x1b90c6 - <unknown>!<bajun_runtime::RuntimeCall as sp_runtime::traits::Dispatchable>::dispatch::h1e953c0ad270c4d2
    6: 0x14ed8d - <unknown>!<sp_runtime::generic::checked_extrinsic::CheckedExtrinsic<AccountId,Call,Extra> as sp_runtime::traits::Applyable>::apply::h63066e3dd511455b
    7: 0x27d0f5 - <unknown>!frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPalletsWithSystem,COnRuntimeUpgrade>::apply_extrinsic::hb105ce907a92d0f9
    8: 0x2a7896 - <unknown>!BlockBuilder_apply_extrinsic. Dropping.
2023-11-06 10:38:30 [Parachain] panicked at 'set_validation_data inherent needs to be present in every block!', /home/builder/cargo/git/checkouts/polkadot-sdk-cff69157b985ed76/f60318f/cumulus/pallets/parachain-system/src/lib.rs:248:13
2023-11-06 10:38:30 [Parachain] err=Error { inner: Proposing
Caused by:
    0: Error at calling runtime api: Execution failed: Execution aborted due to trap: wasm trap: wasm `unreachable` instruction executed
       WASM backtrace:
       error while executing at wasm backtrace:
           0: 0x372f84 - <unknown>!rust_begin_unwind
           1: 0x3228d2 - <unknown>!core::panicking::panic_fmt::hf5c4cd929d4aaa9e
           2: 0x155828 - <unknown>!<cumulus_pallet_parachain_system::pallet::Pallet<T> as frame_support::traits::hooks::OnFinalize<<<<T as frame_system::pallet::Config>::Block as sp_runtime::traits::HeaderProvider>::HeaderT as sp_runtime::traits::Header>::Number>>::on_finalize::h34e87e0da54a8f27
           3: 0x27da40 - <unknown>!frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPalletsWithSystem,COnRuntimeUpgrade>::idle_and_finalize_hook::h0724321d9dba92d2
           4: 0x27dc99 - <unknown>!frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPalletsWithSystem,COnRuntimeUpgrade>::finalize_block::hd8b056510bfa4d57
           5: 0x2a793f - <unknown>!BlockBuilder_finalize_block
    1: Execution failed: Execution aborted due to trap: wasm trap: wasm `unreachable` instruction executed
       WASM backtrace:
       error while executing at wasm backtrace:
           0: 0x372f84 - <unknown>!rust_begin_unwind
           1: 0x3228d2 - <unknown>!core::panicking::panic_fmt::hf5c4cd929d4aaa9e
           2: 0x155828 - <unknown>!<cumulus_pallet_parachain_system::pallet::Pallet<T> as frame_support::traits::hooks::OnFinalize<<<<T as frame_system::pallet::Config>::Block as sp_runtime::traits::HeaderProvider>::HeaderT as sp_runtime::traits::Header>::Number>>::on_finalize::h34e87e0da54a8f27
           3: 0x27da40 - <unknown>!frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPalletsWithSystem,COnRuntimeUpgrade>::idle_and_finalize_hook::h0724321d9dba92d2
           4: 0x27dc99 - <unknown>!frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPalletsWithSystem,COnRuntimeUpgrade>::finalize_block::hd8b056510bfa4d57
           5: 0x2a793f - <unknown>!BlockBuilder_finalize_block }
2023-11-06 10:38:31 [Relaychain] :zzz: Idle (11 peers), best: #7801225 (0x83d9…1f03), finalized #7801221 (0x6bd1…ada0), :arrow_down: 14.2kiB/s :arrow_up: 12.4kiB/s
2023-11-06 10:38:31 [Parachain] :zzz: Idle (4 peers), best: #2336953 (0x3804…e424), finalized #2336953 (0x3804…e424), :arrow_down: 0.7kiB/s :arrow_up: 1.8MiB/s
2023-11-06 10:38:36 [Relaychain] :sparkles: Imported #7801226 (0x4181…ed3d)
2023-11-06 10:38:36 [Relaychain] :recycle:  Reorg on #7801226,0x4181…ed3d to #7801226,0x95a1…f5d9, common ancestor #7801225,0x83d9…1f03
2023-11-06 10:38:36 [Relaychain] :sparkles: Imported #7801226 (0x95a1…f5d9)
2023-11-06 10:38:36 [Relaychain] :zzz: Idle (10 peers), best: #7801226 (0x95a1…f5d9), finalized #7801223 (0x18a0…7309), :arrow_down: 75.3kiB/s :arrow_up: 108.0kiB/s
2023-11-06 10:38:36 [Parachain] :zzz: Idle (4 peers), best: #2336953 (0x3804…e424), finalized #2336953 (0x3804…e424), :arrow_down: 0.6kiB/s :arrow_up: 1.8MiB/s
2023-11-06 10:38:41 [Relaychain] :zzz: Idle (10 peers), best: #7801226 (0x95a1…f5d9), finalized #7801223 (0x18a0…7309), :arrow_down: 55.7kiB/s :arrow_up: 163.8kiB/s
2023-11-06 10:38:41 [Parachain] :zzz: Idle (4 peers), best: #2336953 (0x3804…e424), finalized #2336953 (0x3804…e424), :arrow_down: 0.7kiB/s :arrow_up: 1.9MiB/s
2023-11-06 10:38:42 [Relaychain] :sparkles: Imported #7801227 (0x7516…eb87)
```

**Additional Information**

Our thoughts are that the experimental flag got not activated.

We set MinimumPeriod = 0, and were expecting that through the experimental flag it was not being used any more

assert!(!slot_duration.is_zero(), "Aura slot duration cannot be zero.");
https://github.com/paritytech/polkadot-sdk/blob/f60318f68687e601c47de5ad5ca88e2c3f8139a7/substrate/frame/aura/src/lib.rs#L406C7-L406C7

seems like we don't get the experimental set properly.

	/// Determine the Aura slot-duration based on the Timestamp module configuration.
	pub fn slot_duration() -> T::Moment {
		#[cfg(feature = "experimental")]
		{
			T::SlotDuration::get()
		}

		#[cfg(not(feature = "experimental"))]
		{
			// we double the minimum block-period so each author can always propose within
			// the majority of its slot.
			<T as pallet_timestamp::Config>::MinimumPeriod::get().saturating_mul(2u32.into())
		}
	}

**Steps done sofar**

To make sure the experimental flag is activated in the wasm, we did a local build

```
cargo clean --release
cargo -vv build-bajun &> build.log
```
and we verified the build log for the experimental flag finding 3 references including pallet_aura and then sent the upgrade to be set directly on rococo with santiago
Deployed -> https://rococo.subscan.io/extrinsic/0xf29a3cc9fe9c34b71ec2e6b53647e0c431a46662cd8abf8dbb100a529f6a9661

Then resynced collators, but panick still happend.

**Comment by Sophia-Gold** [comment]
Try adding something like this:

```
	#[cfg(feature = "experimental")]
	type MinimumPeriod = ConstU64<0>;
	#[cfg(not(feature = "experimental"))]
	type MinimumPeriod = ConstU64<{ SLOT_DURATION / 2 }>;
```
here: https://github.com/ajuna-network/Ajuna/blob/v0.1.25/runtime/bajun/src/lib.rs#L327

**Comment by darkfriend77** [comment]
solved
